spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ep-dry-silence-88056814-pooler.ap-southeast-1.aws.neon.tech/neondb?user=hamjiruschai&password=AQcmdHCwt4u2
    username: hamjiruschai
    password: AQcmdHCwt4u2
---
app:
  token:
    secret: m#MySecretEGCO33+34
    issuer: BackendService
